### ISSUE TITLE
[imporvement] - consider to remove react-bootstrap package 

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/Developer_Quiz_Site#1211]
### What bug did you find in the codebase?

currently the project uses react-bootstrap package for styles.
as far as i can see - there is no big need for `bootstrap` styles in the project...
(only the modal actually makes use of bootstrap package - but it can be implemented in other ways )
it can be nice to move to tailwind styling as it in the main project

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I've removed the Bootstrap and react-bootstrap dependencies from the project and implemented a custom modal component. This change eliminates the need for these external libraries while maintaining the functionality of the quiz modal. Here's a summary of the changes:

1. Removed Bootstrap and react-bootstrap from package.json
2. Created a new custom Modal component
3. Updated QuizModal to use the new custom Modal
4. Adjusted styles to maintain the look and feel without Bootstrap

These changes reduce the project's dependencies and give more control over the styling and behavior of the modal.

I also created pull request: https://github.com/freeCodeCamp/Developer_Quiz_Site/pull/1212


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by jdwilkin4** [comment]
> it can be nice to move to tailwind styling as it in the main project

I don't see a need to move to tailwind. Using regular CSS for this project is fine.
The main repo uses tailwind but it is on a completely different scale and manages way more components and styles then this one.

**Comment by shootermv** [comment]
It is makes sense that tailwind is overkill
