### ISSUE TITLE
Need a database for Quiz questions. fullQuiz

### ISSUE THREAD

**Issue by Starboy-Sharma** [freeCodeCamp/Developer_Quiz_Site#30]
As we want to increase more quiz questions (Python, SQL, JS) our array size of fullQuiz started to increase. We are also performing shuffle on the array items later things start working slow. Right now we have all categories of questions in a single array. Later if we want to play a Quiz only for JS we can not do this because we do not have a property like language. (SQL, JS).

This is what I feel we can improve.

**Comment by jdwilkin4** [comment]
Hi @Starboy-Sharma ! 

Thank you for your issue.

For the initial release, we just decided on the one array because we didn't have a whole lot of questions.
But the goal was always to have multiple categories once we beefed up the SQL, CS and IT sections.

> Later if we want to play a Quiz only for JS we can not do this because we do not have a property like language. 

That is something we are going to change and eventually the user can choose their category and number of questions.
