### ISSUE TITLE
[Feature] - Tweet button located on the results page

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/Developer_Quiz_Site#388]
### What feature would you like to see?

I want to add to add button or link that allows the completer of the quiz to share their score on Twitter populated with the text "I just scored X% on the <quiz name> - try it yourself? <link>". I believe using Tweet intents would be the best avenue to go about this problem.

**Comment by jdwilkin4** [comment]
A couple of things to iron out and discuss

No.1: Let's change the wording for the tweet link
Right now it says "Share on Twitter?" but maybe we can try one of these other options.
- Tweet your quiz score
- Wanna tweet your quiz score?
or something along those lines that includes the words "quiz score"

Also, maybe we could incorporate the twiter icon somehow.
I like how they are using for the Learn to Code RPG game here
 
<img width="341" alt="Screen Shot 2022-10-14 at 12 58 25 PM" src="https://user-images.githubusercontent.com/67210629/195931603-5a2bb354-1d05-4598-bb49-fdb730ec252a.png">

maybe we can do something similar here. 

No.2: polishing the tweet message

Right it says "% on the Learn to Code An RPG developer quiz - try it yourself?"
I think we can just go with developerquiz.org instead of  Learn to Code An RPG developer quiz.

But also if we can match something similar to these tweets from the Learn to Code RPG game

<img width="607" alt="Screen Shot 2022-10-14 at 1 01 38 PM" src="https://user-images.githubusercontent.com/67210629/195932119-76ee0f8d-f860-4348-81c6-c87e7f91f519.png">

I don't know if it is possible to incorporate some sort of image in the tweet but I think that would help with engagement. If it is possible we could probably just use a coding image from something like unsplash.

Maybe we could also include the hashtag for freeCodeCamp. 

If you could play around with those suggestions and reply back with a screenshot for the results page and the tweet, that would be great 👍

**Comment by a2937** [comment]
No.1: Let's change the wording for the tweet link

```Tweet your quiz score```

On it. I'm going to go for the first one. As for the Twitter bird icon; I think we can maybe use Font Awesome here if you aren't already. Or just use the Twitter logo image and display it either above or next to the text. 

No.2: polishing the tweet message

As for the message wording; 

I'll go with the first suggestion. 

For additional features:

- The image is probably a Twitter card as described on here: https://stackoverflow.com/questions/18321649/twitter-web-intent-to-post-image

- As for adding the hashtags, it's as easier as adding another query parameter.

**Comment by jdwilkin4** [comment]
That all sounds good to me 👍

**Comment by a2937** [comment]
I don't have a Twitter and will need someone else to check it out for me.

**Comment by jdwilkin4** [comment]
I can pull down your branch and test it out tomorrow with Twitter 👍
