### ISSUE TITLE
[Feature] - Category Selection options

### ISSUE THREAD

**Issue by dostonnabotov** [freeCodeCamp/Developer_Quiz_Site#563]
### What feature would you like to see?

It would be cool if we could choose the category we want to practice depending on what skills we want to work on. 

For example, if I want to practice JavaScript, I would select the category "JavaScript" and get all JavaScript-related quiz questions.

What do you think about this feature?

**Comment by jdwilkin4** [comment]
Hi @dostonnabotov ! 

This feature was brought up earlier on the in the development of the app but we were still light on questions for most categories. So that is why there was such a huge push for question contributions. 

But Hacktoberfest has ushered in a lot of new questions. Once Hacktoberfest has commenced, then the core team can discuss which categories would be included in this new feature.

**Comment by bbsmooth** [comment]
@jdwilkin4 Do we have enough questions to reopen this issue now? I really like the idea of this quiz but I definitely don't like the idea of getting questions for topics I am not interested in and know nothing about.

**Comment by jdwilkin4** [comment]
We have enough questions in most categories now to do this feature. 
I will create a new issues laying out the criteria and design.
