### ISSUE TITLE
[Feature] - Add ability for users to choose a category

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#657]
### What feature would you like to see?

We now have enough questions to break up the quiz into categories. When the user clicks on the button to start the quiz, they should be directed to this screen here.

## First Slide
<img width="514" alt="Screen Shot 2023-01-12 at 8 51 57 AM" src="https://user-images.githubusercontent.com/67210629/212129832-03862a15-30fa-43c0-ae2c-dd3da6ed9818.png">

Then once a user selects a category, they will be directed to this screen here.

## Second Slide
<img width="668" alt="Screen Shot 2023-01-12 at 8 47 44 AM" src="https://user-images.githubusercontent.com/67210629/212128871-36df348c-ae28-4dff-8700-42b4f80b22a3.png">

Then once a user selects a question amount, they will be directed to the actual quiz here. 

## Quiz
<img width="886" alt="Screen Shot 2023-01-12 at 8 48 10 AM" src="https://user-images.githubusercontent.com/67210629/212128972-09c69658-3975-4300-8fb1-31fd3fd1c9bf.png">

If you are interested in working on this issue, then please reply back to this issue and it will be assigned to you.

**Comment by dostonnabotov** [comment]
Hi, @jdwilkin4.

I am interested in solving this issue. Well, I am not expert in React yet. Still learning and experimenting it along with TypeScript. However, I would be happy to pick this up. Also, since it is a large code base, it would be very helpful if you could "walk through" it just in case I have questions or need some help :)

**Comment by jdwilkin4** [comment]
This issue has been assigned to you 👍

**Comment by dostonnabotov** [comment]
Hi, @jdwilkin4

Since we're adding the select-by-category feature, do we need "Score Breakdown by Category" at the end of quiz? Because at the end of the day, you will only get questions from one category.

![Score Breakdown by Category screenshot](https://user-images.githubusercontent.com/96492656/212552420-bac8fe04-3fcf-45ac-b70b-e34fbd6bf878.png)

And, by removing "Score Breakdown by Category", we might be able to optimize the code as well.

![Score Breakdown by Category code in VS code](https://user-images.githubusercontent.com/96492656/212552832-9c97948d-f72d-4802-8209-c455424c807c.png)

**Comment by jdwilkin4** [comment]
@dostonnabotov 

So I was debating back and forth about whether or not to keep a mixed category and I think it would be better to leave out the mixed category. 

You can remove the score break down at the end. 


> we might be able to optimize the code as well. 

There are a lot of changes that need to be made the codebase but I haven't had time to go through and create a refactor PR.
You are free to optimize the `incrementQuestions` function especially since we are removing a feature. 
For any other refactoring, just make sure that you are within scope of this ticket so the PR will be easy to review.
Any other code refactors that don't relate to this ticket would be better addressed in another issue 👍

**Comment by ProfJoanna** [comment]
Would it be possible to give the users an option to choose multiple categories at the same time ? I could see myself wanting to take an HTML and CSS and JS quiz for example..

**Comment by BekahHW** [comment]
I can take this, @jdwilkin4!

**Comment by jdwilkin4** [comment]
awesome, its all yours @BekahHW

**Comment by BekahHW** [comment]
@jdwilkin4 Do you only want the categories shown in the screenshot above? I know there are more in the ALL_CATEGORIES file. Along the same lines, do you want a "random" category that preserves the current functionality?

**Comment by jdwilkin4** [comment]
@BekahHW 

> Do you only want the categories shown in the screenshot above?

Yes, let's start with the categories listed in the screenshot because I know there are plenty of questions to choose from. 
Some of the other categories that were recently added don't have enough questions yet so let's leave those out for now. 


> Along the same lines, do you want a "random" category that preserves the current functionality?

Yes, I think that would be nice. Thanks!
