### ISSUE TITLE
Auto Response Github Action

### ISSUE THREAD

**Issue by naomi-lgbt** [freeCodeCamp/Developer_Quiz_Site#663]
Making a note for myself here.

In preparation for Hacktoberfest 2023, we want to add an action that auto-responds to pull requests (from Camperbot) thanking the contributor, asking for patience, and letting them know that we will review the pr when we are available.

This should cut down on the mention spam.

**Comment by ht-l1** [comment]
hey will we have the "new issues" set up for 2023 Hacktoberfest opening up soon? I see 2022 issues are locked even they are marked as open

**Comment by jdwilkin4** [comment]
HI @ht-l1 ! 

All of the issues open, with the exception of this one, are available for contribution for hacktoberfest 2023.
We are still looking for quiz questions in those specific areas which is why they remained open issues.

> will we have the "new issues" set up for 2023 Hacktoberfest opening up soon?

we had a few small issues open up at the beginning of the month, but all of those have since been resolved which is why they are closed. 

As for why the remaining issues are locked, there were a lot of conversations going on that didn't have to deal with the issue so we moved all conversations over to GitHub discussions.
https://github.com/freeCodeCamp/Developer_Quiz_Site/discussions

Hope that answers your question.
If you have any other questions, please feel free to reach out in the GitHub discussions and we can assist you there 👍

**Comment by naomi-lgbt** [comment]
Going to close this as we now have the ability to post reminders from Camperbot's account through Discord.
