### ISSUE TITLE
[Bug] - 404 from appear when refreshing browser after starting quiz

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/Developer_Quiz_Site#939]
### What bug did you find in the codebase?

when  accessing `quizzes` route and then tries to refresh a window 
 the site displays 404 error

**Comment by jdwilkin4** [comment]
It looks like the issue still persists in production.

Tried testing it locally with `npm run preview` command after a locally build and it works fine. 
But the error is still there in production.

We could try refactoring the app to use hash router instead of browser router
https://stackoverflow.com/questions/63462828/404-error-on-refresh-with-spa-react-router-app-in-github-pages

It would add a `#` to our URL but it might resolve the issue of the 404 error on refresh
