### ISSUE TITLE
Enchancement: Question number at the top

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/Developer_Quiz_Site#94]
I was wondering if the question number can go up into the h1 heading as some of the questions are a little longer and it stretches across the entire screen; while the actual question goes into a paragraph tag below it.

**Comment by jdwilkin4** [comment]
You are suggested this type of change?
<img width="1239" alt="Screen Shot 2022-07-31 at 5 15 56 PM" src="https://user-images.githubusercontent.com/67210629/182051458-9fadc5d6-bff5-4815-8e40-03ceb0119268.png">

**Comment by a2937** [comment]
Not quite. 

![What I actually mean](https://i.imgur.com/T8O6XUN.png)

**Comment by a2937** [comment]
This is more along what I actually meant. Question in a text-centered paragraph tag while the actual question number is the heading.

**Comment by jdwilkin4** [comment]
The font size for the question should be a little bit larger than the `Questions:1/10` and `Points` text. 
Since the question holds more importance then the `Questions:1/10` and `Points` text, it should stand out a little bit more. 
Maybe you can play around with the `rem/em` values to increase the size.

**Comment by jdwilkin4** [comment]
Hi @a2937 ! 

If you are still in interested in working on this, we will keep this open with your name assigned to it. 
Otherwise, you can close this issue if you are no longer interested.

**Comment by a2937** [comment]
I'll be happy to work on it.
